### ISSUE TITLE
Documentation string location

### ISSUE THREAD

**Issue by randallsummers** [Shinmera/staple#18]
Hello,

Apologies if this question is better asked elsewhere, but I was wondering where your documentation strings are located in this project? When I look at your source, I don't see any documentation strings in your code, but you generated documentation makes it look as if you do have documentation strings. Sorry again if I'm missing something obvious.

Thanks!

**Comment by Shinmera** [comment]
You're missing a file called [`documentation.lisp`](https://github.com/Shinmera/staple/blob/master/documentation.lisp)
