### ISSUE TITLE
SRC links should reference commit

### ISSUE THREAD

**Issue by Shinmera** [Shinmera/staple#24]
Currently the source links refer to master, which will become desynced with the documentation's baked-in source lines. The documentation should link to the current commit at the time of compilation instead.

**Comment by Shinmera** [comment]
To this end we should probably have a generic "version" in the project that can be automatically determined in git-powered projects (with a protocol to support others).

This versioning could also be used to determine whether a change has occurred at all and the docs need to be rebuilt.

**Comment by lockie** [comment]
A reasonable approach (or at least its part) seems to grab the `:version` from ASDF definition and point the link to the correspoding Git tag, but the package author would have to (a) create a tag, and (b) make tag's name coincide with the version. Also there is _releases_ mechanism on both Github and Gitlab, but it is optional and again requires some extra work from the package author.

**Comment by Shinmera** [comment]
In 9c76782 I've made it just  try to use the git binary to get the current hash, which should work for 99%. For the rest you can customise what ``current-commit`` returns for your system.

**Comment by lockie** [comment]
Awesome, thanks!
