### ISSUE TITLE
Minor layout issue

### ISSUE THREAD

**Issue by lockie** [Shinmera/staple#27]
Hi!
I've noticed that when the package have a long list of dependencies, in generated HTML the word "Dependenices" sticks to the list in "System Information" section (in latest Chrome at least), e.g. even in https://shinmera.github.io/staple :

![2020-02-08-103724_536x183_scrot](https://user-images.githubusercontent.com/160056/74081352-17ced180-4a5f-11ea-95c8-03f9df59c4f2.png)

Setting CSS property `min-width` on `article.project .row label` to at least `7em` fixes the issue:

![2020-02-08-104102_600x60_scrot](https://user-images.githubusercontent.com/160056/74081380-8875ee00-4a5f-11ea-90ea-215eef23709e.png)

**Comment by lockie** [comment]
@Shinmera Hey Nicolas, would you be accepting a pull request to fix this?

**Comment by Shinmera** [comment]
PRs are always welcome!

**Comment by Shinmera** [comment]
Sorry for not getting back to you sooner, this got buried somehow. In my browser the mentioned issue does not appear: 

![2020-03-23-172434_931x211_scrot](https://user-images.githubusercontent.com/4833204/77338866-3f39df00-6d2b-11ea-8ea5-966dbdecfa9d.png)

So this seems to be system setup dependent and a smarter fix than increasing the max width might be necessary.

**Comment by lockie** [comment]
No problem!
You're using Mac, I presume? What is the font your browser uses to render that `dependencies` text?

**Comment by Shinmera** [comment]
I'm not, no. I'm using Concourse T3 as the default sans-serif font.

**Comment by lockie** [comment]
Oh I see. I'll investigate this deeper.

**Comment by lockie** [comment]
It also reproduces on IE11 with its default terrible fonts:

![2020-03-23-193933_949x271_scrot](https://user-images.githubusercontent.com/160056/77340348-38689780-6d3e-11ea-8868-38c7f2630821.png)
