### ISSUE TITLE
Issue with markdown parser?

### ISSUE THREAD

**Issue by anlsh** [Shinmera/staple#30]
I have a function whose source code is as follows
```
(defun combinations-with-rep (iterlike r)
      "r-combinations with replacement of input iterable, returned as vectors in lexicographic
      order
      ```
      (combinations (1 2 3) 2)
      => #(1 1), #(1 2), #(1 3), #(2 1), #(2 2), #(2 3), #(3 1), #(3 2), #(3 3)
      ```"
      (let ((pool (iter-to-vec iterlike)))
        (init-state r
                    (n (length pool))
                    (pool pool)
                    (indices (iter-to-vec (repeat 0 r))))))
```

Unfortunately the markdown parser renders the docstring blurb and code block as part of the same line when running `(staple:generate :my-system)` (I think this itself is an issue, since Github and Reddit markdown both work otherwise).

Anyways, if I try to fix the issue by adding a newline between the "order" and triple-backquote lines, then `staple:generate` reports the following error
```
WARN: Error during code markup: Unquote not inside backquote.
```
which seems totally irrelevant to the actual "problem"

I have a two questions

1. Exactly what parser is being used, or which markdown format is accepted?
2. Is it possible to change this parser/format to something more standard?
3. Would it be possible to have the markdown parser signal some location info (file, line number, method, macro, etc) for problematic docstrings? I had to figure this out by commenting and uncommenting things everywhere

**Comment by anlsh** [comment]
My `staple.ext.lisp` is below just for completeness: it's ripped off from the example provided in the README :D

```
(ql:quickload :staple-markdown)

(defclass my-page (staple:simple-page) ())

(defmethod staple:page-type ((system (eql (asdf:find-system :picl))))
  'my-page)

(defmethod staple:packages ((system (eql (asdf:find-system :picl))))
  (mapcar #'find-package '(:picl)))

(defmethod staple:format-documentation ((docstring string) (page my-page))
  (let ((*package* (first (staple:packages page))))
    (staple:markup-code-snippets-ignoring-errors
     (staple:compile-source docstring :markdown))))
```

**Comment by Shinmera** [comment]
I can't take a closer look at it right now but my immediate guess would be that the leading spaces in the docstring are tripping things up.

**Comment by anlsh** [comment]
I actually had the same thought, but that's not it: I get the same behavior with the attached snippet (attached because I can't figure out how to render it correctly)

[foo.txt](https://github.com/Shinmera/staple/files/4873973/foo.txt)

**Comment by Shinmera** [comment]
Oh wait I see the problem now. Of course. Staple attempts to parse the code block into actual valid Lisp forms. Having a comma outside a backquote like you do on the `=>` line, is naturally illegal, and that's what it complains about. My recommendation is to put a `;` in front of the `=>` to turn it into valid Lisp code.

**Comment by anlsh** [comment]
I don't see why the whitespace would make a difference in signalling the error, but I've gotten it working now. Thank you!

**Comment by Shinmera** [comment]
I'm not sure either, might be a problem with 3bmd.
