### ISSUE TITLE
Package detection

### ISSUE THREAD

**Issue by fare** [Shinmera/staple#4]
Couldn't you use a `(defmethod perform :after ((o prepare-op) (s system)) ...)` and a `(defmethod perform ((o load-op) (s system)) ...)` to record all the packages in existence before and after a system is loaded?

**Comment by Shinmera** [comment]
Possibly, but if I understand right, that would require the system to document be explicitly loaded after staple, yes?

**Comment by fare** [comment]
Indeed.

**Comment by fare** [comment]
Looks Good To Me. Congrats!

(Well, I think the way you store the intermediate results is a bit distasteful, but, oh well.)

**Comment by Shinmera** [comment]
I'm not happy with that either, to be honest. Any suggestions?

**Comment by fare** [comment]
No great suggestions, except that there should probably be separate tables for "packages we know have been created by this system" and "packages known to exist before this system". Especially since, when you load a system twice, etc., you may want to *add* to the first, rather than overwrite it — or else, the second time will erase all the information.

**Comment by Shinmera** [comment]
Ah, yeah, I hadn't thought of that case.
